name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  animations:
    name: Animation files

    permissions:
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Get changed animations
        id: changed-animations
        uses: tj-actions/changed-files@v47
        with:
          files: |
            animations/**/*.json

      - name: Install packages
        if: steps.changed-animations.outputs.any_changed == 'true'
        run: npm install

      - name: Check formatting with Prettier
        if: steps.changed-animations.outputs.any_changed == 'true'
        run: |
          npx prettier --check ${{ steps.changed-animations.outputs.all_changed_files }}
      - name: Test animation files
        if: steps.changed-animations.outputs.any_changed == 'true'
        # env:
        #   MODIFIED_ANIMATIONS: ${{ steps.changed-animations.outputs.all_changed_files }}
        run: "npm run test:animations" # -- ${MODIFIED_ANIMATIONS}
